In [1]:
import pandas as pd
import numpy as np 
df=pd.read_csv(r"SuperMarket Analysis.csv")
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,1:46:00 PM,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,1:22:00 PM,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,3:33:00 PM,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

In [4]:
# Har City Ka sales Revenue
df.groupby('City')['Sales'].sum()

City
Mandalay     106197.6720
Naypyitaw    110568.7065
Yangon       106200.3705
Name: Sales, dtype: float64

In [5]:
# Har Branch ki total Gross Income calculate karo.  

df.groupby('Branch')['gross income'].sum()

Branch
Alex     5057.1605
Cairo    5057.0320
Giza     5265.1765
Name: gross income, dtype: float64

In [ ]:

print(df.groupby('Product line')[['Sales','Quantity']].sum())

                             Sales  Quantity
Product line
Electronic accessories  54337.5315       971
Fashion accessories     54305.8950       902
Food and beverages      56144.8440       952
Health and beauty       49193.7390       854
Home and lifestyle      53861.9130       911
Sports and travel       55122.8265       920

In [26]:
# Kaunsa Product Line sabse zyada revenue generate karta hai? 
print(df.groupby('Product line')['Sales'].sum().sort_values(ascending=False).head(1))

Product line
Food and beverages    56144.844
Name: Sales, dtype: float64

In [27]:
print(df.groupby('Product line')['Sales'].sum().sort_values(ascending=False).tail(1))

Product line
Health and beauty    49193.739
Name: Sales, dtype: float64

In [28]:
# Har Branch ka average Unit Price calculate karo. 

df.groupby('Branch')['Unit price'].mean()

Branch
Alex     54.780853
Cairo    55.659277
Giza     56.609024
Name: Unit price, dtype: float64

In [29]:
# Har City ka average Sales per transaction calculate karo.

df.groupby('City')['Sales'].mean()

City
Mandalay     319.872506
Naypyitaw    337.099715
Yangon       312.354031
Name: Sales, dtype: float64

In [38]:
# Top 10 highest-value transactions identify karo based on Sales. 
df['Sales'].sort_values(ascending=False).head(10)

350    1042.650
167    1039.290
557    1034.460
699    1023.750
996    1022.490
792    1022.385
422    1020.705
166    1003.590
357    1002.120
429     951.825
Name: Sales, dtype: float64

In [45]:
Low = []
Medium = []
High = []

for i in df['Sales']:
    if i < 200:
        Low.append(i)
    elif i < 700:
        Medium.append(i)
    else:
        High.append(i)

In [55]:
def categorize(sales):
    if sales < 200:
        return "Low"
    elif sales < 700:
        return "Medium"
    else:
        return "High"

df['Division'] = df['Sales'].apply(categorize)
df['Division']

0      Medium
1         Low
2      Medium
3      Medium
4      Medium
        ...
995       Low
996      High
997       Low
998       Low
999    Medium
Name: Division, Length: 1000, dtype: str

In [57]:
#  Har City mein Member vs Normal customers ki count nikalo.

df.groupby('City')['Customer type'].value_counts()

City       Customer type
Mandalay   Member           181
           Normal           151
Naypyitaw  Member           194
           Normal           134
Yangon     Member           190
           Normal           150
Name: count, dtype: int64

In [62]:
''' Member customers ki total Sales aur Normal customers ki total Sales compare karo.'''

df.groupby('Customer type')['Sales'].sum()/df['Sales'].sum()*100

Customer type
Member    58.735076
Normal    41.264924
Name: Sales, dtype: float64

In [63]:
# Female aur Male customers ki total Sales compare karo

df.groupby('Gender')['Sales'].sum()/df['Sales'].sum()*100

Gender
Female    60.276124
Male      39.723876
Name: Sales, dtype: float64

In [71]:
# Har Product Line mein Female aur Male customers ki Sales calculate karo.

df.groupby('Product line')[['Gender','Sales']].value_counts()

Product line            Gender  Sales
Electronic accessories  Male    87.2340     2
                        Female  80.2200     1
                                627.6165    1
                                433.6920    1
                                107.1420    1
                                           ..
Sports and travel       Male    92.7255     1
                                53.1510     1
                        Female  469.7700    1
                                921.1860    1
                                804.3000    1
Name: count, Length: 997, dtype: int64

In [72]:
#  Kis Customer Type ka average Rating highest hai?

df.groupby('Customer type')['Rating'].mean()

Customer type
Member    6.917168
Normal    7.044828
Name: Rating, dtype: float64

In [78]:
#  Har City mein Member customers ka percentage calculate karo.

df2 = df[df['Customer type']== "Member"]
df2.groupby('City')['Customer type'].value_counts()/df['Customer type'].count()*100

City       Customer type
Mandalay   Member           18.1
Naypyitaw  Member           19.4
Yangon     Member           19.0
Name: count, dtype: float64

In [80]:
# Har Branch mein Female customers ki percentage calculate karo. 

df3 = df[df['Gender']== "Female"]
df3.groupby('Branch')['Gender'].value_counts()/df['Gender'].count()*100

Branch  Gender
Alex    Female    18.7
Cairo   Female    18.4
Giza    Female    20.0
Name: count, dtype: float64

In [83]:
#  Identify karo ki kis Product Line mein Member customers sabse zyada hain.  

df2.groupby('Product line')['Customer type'].value_counts().sort_values(ascending=False)

Product line            Customer type
Food and beverages      Member           104
Sports and travel       Member            97
Fashion accessories     Member            96
Home and lifestyle      Member            92
Electronic accessories  Member            90
Health and beauty       Member            86
Name: count, dtype: int64

In [87]:
# Customer Type aur Gender ke combination se total Sales nikalo.  

f = df.groupby('Customer type')[['Gender','Sales']].value_counts()
f.to_csv(r'C:\Users\great\OneDrive\Desktop\hello.csv')

In [90]:
# Aise transactions count karo jahan Quantity > 5 aur Customer Type = Member ho. 

df2[df2['Quantity']>5]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Division
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1,Medium
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4,Medium
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3,Medium
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1,Medium
6,355-53-5943,Alex,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,2:36:00 PM,Ewallet,413.04,4.761905,20.6520,5.8,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982,139-32-4183,Alex,Yangon,Member,Female,Sports and travel,97.48,9,43.8660,921.1860,3/14/2019,2:19:00 PM,Ewallet,877.32,4.761905,43.8660,7.4,High
987,552-44-5977,Cairo,Mandalay,Member,Male,Health and beauty,62.00,8,24.8000,520.8000,1/3/2019,7:08:00 PM,Credit card,496.00,4.761905,24.8000,6.2,Medium
988,267-62-7380,Giza,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.1700,864.5700,3/29/2019,7:12:00 PM,Ewallet,823.40,4.761905,41.1700,4.3,High
989,430-53-4718,Cairo,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,1/28/2019,3:46:00 PM,Credit card,602.96,4.761905,30.1480,8.4,Medium
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6,Medium

In [93]:
'''Har Product Line ki average Quantity per transaction calculate karo. '''

df.groupby('Product line')['Quantity'].mean()

Product line
Electronic accessories    5.711765
Fashion accessories       5.067416
Food and beverages        5.471264
Health and beauty         5.618421
Home and lifestyle        5.693750
Sports and travel         5.542169
Name: Quantity, dtype: float64

In [94]:
#  Kaunsa Product Line sabse zyada average Quantity sell karta hai?

df.groupby('Product line')['Quantity'].mean().sort_values(ascending=False).head(1)

Product line
Electronic accessories    5.711765
Name: Quantity, dtype: float64

In [95]:
#  Har Product Line ka minimum aur maximum Unit Price nikalo. 
df.groupby('Product line')['Unit price'].agg(['min', 'max'])

                          min    max
Product line
Electronic accessories  10.56  99.73
Fashion accessories     10.18  99.89
Food and beverages      10.13  99.79
Health and beauty       10.08  99.96
Home and lifestyle      10.53  99.92
Sports and travel       10.17  99.96

In [96]:
#  Aise products/transactions identify karo jahan Unit Price 50 se zyada hai. 

df[df['Unit price'] > 50]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Division
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1,Medium
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4,Medium
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3,Medium
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1,Medium
6,355-53-5943,Alex,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,2:36:00 PM,Ewallet,413.04,4.761905,20.6520,5.8,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,745-74-0715,Alex,Yangon,Normal,Male,Electronic accessories,58.03,2,5.8030,121.8630,3/10/2019,8:46:00 PM,Ewallet,116.06,4.761905,5.8030,8.8,Low
994,652-49-6720,Giza,Naypyitaw,Member,Female,Electronic accessories,60.95,1,3.0475,63.9975,2/18/2019,11:40:00 AM,Ewallet,60.95,4.761905,3.0475,5.9,Low
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4,High
998,347-56-2442,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,3:33:00 PM,Cash,65.82,4.761905,3.2910,4.1,Low
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6,Medium

In [97]:
#  Aise transactions count karo jahan Quantity 10 hai. 

df[df['Quantity'] == 10]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Division
7,315-22-5665,Giza,Naypyitaw,Member,Female,Home and lifestyle,73.56,10,36.780,772.380,2/24/2019,11:38:00 AM,Ewallet,735.6,4.761905,36.780,8.0,High
13,252-56-2699,Alex,Yangon,Member,Female,Food and beverages,43.19,10,21.595,453.495,2/7/2019,4:48:00 PM,Ewallet,431.9,4.761905,21.595,8.2,Medium
14,829-34-3910,Alex,Yangon,Member,Female,Health and beauty,71.38,10,35.690,749.490,3/29/2019,7:21:00 PM,Cash,713.8,4.761905,35.690,5.7,High
49,574-22-5561,Giza,Naypyitaw,Member,Female,Fashion accessories,82.63,10,41.315,867.615,3/19/2019,5:08:00 PM,Ewallet,826.3,4.761905,41.315,7.9,High
58,817-48-8732,Alex,Yangon,Member,Female,Home and lifestyle,72.35,10,36.175,759.675,1/20/2019,3:55:00 PM,Cash,723.5,4.761905,36.175,5.4,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,746-04-1077,Cairo,Mandalay,Member,Female,Food and beverages,84.63,10,42.315,888.615,1/1/2019,11:36:00 AM,Credit card,846.3,4.761905,42.315,9.0,High
988,267-62-7380,Giza,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.170,864.570,3/29/2019,7:12:00 PM,Ewallet,823.4,4.761905,41.170,4.3,High
991,602-16-6955,Cairo,Mandalay,Normal,Female,Sports and travel,76.60,10,38.300,804.300,1/24/2019,6:10:00 PM,Ewallet,766.0,4.761905,38.300,6.0,High
993,690-01-6631,Cairo,Mandalay,Normal,Male,Fashion accessories,17.49,10,8.745,183.645,2/22/2019,6:35:00 PM,Ewallet,174.9,4.761905,8.745,6.6,Low
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.690,1022.490,3/2/2019,5:16:00 PM,Ewallet,973.8,4.761905,48.690,4.4,High

In [99]:
# Har Product Line ka total COGS calculate karo
df.groupby('Product line')['cogs'].sum()

Product line
Electronic accessories    51750.03
Fashion accessories       51719.90
Food and beverages        53471.28
Health and beauty         46851.18
Home and lifestyle        51297.06
Sports and travel         52497.93
Name: cogs, dtype: float64

In [103]:
# Date column se Month extract karo
df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.month_name()
df['Month']

0       January
1         March
2         March
3       January
4      February
         ...
995     January
996       March
997    February
998    February
999    February
Name: Month, Length: 1000, dtype: str

In [104]:
#  Har month ki total Sales calculate karo
df.groupby('Month')['Sales'].sum()

Month
February     97219.374
January     116291.868
March       109455.507
Name: Sales, dtype: float64

In [105]:
# Har month ki total Gross Income calculate karo.  

df.groupby('Month')['gross income'].sum()

Month
February    4629.494
January     5537.708
March       5212.167
Name: gross income, dtype: float64

In [ ]:

df.groupby('Month')['Sales'].sum().sort_values(ascending=False).head(1)

Month
January    116291.868
Name: Sales, dtype: float64

In [110]:
# Kaunsa month lowest Sales generate karta hai?  
df.groupby('Month')['Sales'].sum().sort_values(ascending=False).tail(1)

Month
February    97219.374
Name: Sales, dtype: float64

In [113]:
# Date se Day Name (Monday, Tuesday...) extract karo.
df['Day'] = df['Date'].dt.day_name()
df['Day']

0      Saturday
1        Friday
2        Sunday
3        Sunday
4        Friday
         ...
995     Tuesday
996    Saturday
997    Saturday
998      Friday
999      Monday
Name: Day, Length: 1000, dtype: str

In [114]:
#  Har weekday ki total Sales calculate karo.  

df.groupby('Day')['Sales'].sum()

Day
Friday       43926.3405
Monday       37899.0780
Saturday     56120.8095
Sunday       44457.8925
Thursday     45349.2480
Tuesday      51482.2455
Wednesday    43731.1350
Name: Sales, dtype: float64

In [120]:
# . Kaunsa weekday highest average Sales generate karta hai?  

df.groupby('Day')['Sales'].mean().sort_values(ascending=False).head(1)

Day
Saturday    342.200058
Name: Sales, dtype: float64

In [122]:
# Time column se Hour extract karo. 
df['Hour'] = pd.to_datetime(df['Time']).dt.hour
df['Hour']

C:\Users\great\AppData\Local\Temp\ipykernel_25920\2306386046.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Hour'] = pd.to_datetime(df['Time']).dt.hour

0      13
1      10
2      13
3      20
4      10
       ..
995    13
996    17
997    13
998    15
999    13
Name: Hour, Length: 1000, dtype: int32

In [123]:
# Morning, Afternoon aur Evening ke according transactions categorize karo.

df['Time_Category'] = df['Hour'].apply(lambda x: 'Morning' if 6 <= x < 12 else ('Afternoon' if 12 <= x < 18 else 'Evening'))
df['Time_Category']

0      Afternoon
1        Morning
2      Afternoon
3        Evening
4        Morning
         ...
995    Afternoon
996    Afternoon
997    Afternoon
998    Afternoon
999    Afternoon
Name: Time_Category, Length: 1000, dtype: str

In [124]:
#  City + Product Line ke basis par total Sales nikalo using 

df.groupby(['City','Product line'])['Sales'].sum()

City       Product line
Mandalay   Electronic accessories    17051.4435
           Fashion accessories       16413.3165
           Food and beverages        15214.8885
           Health and beauty         19980.6600
           Home and lifestyle        17549.1645
           Sports and travel         19988.1990
Naypyitaw  Electronic accessories    18968.9745
           Fashion accessories       21560.0700
           Food and beverages        23766.8550
           Health and beauty         16615.3260
           Home and lifestyle        13895.5530
           Sports and travel         15761.9280
Yangon     Electronic accessories    18317.1135
           Fashion accessories       16332.5085
           Food and beverages        17163.1005
           Health and beauty         12597.7530
           Home and lifestyle        22417.1955
           Sports and travel         19372.6995
Name: Sales, dtype: float64

In [126]:
# Branch + Customer Type + Gender ke basis par transaction count nikalo using  COUNTIFS

df.groupby(['Branch', 'Customer type', 'Gender']).count()

                             Invoice ID  City  Product line  Unit price  \
Branch Customer type Gender
Alex   Member        Female         112   112           112         112
                     Male            78    78            78          78
       Normal        Female          75    75            75          75
                     Male            75    75            75          75
Cairo  Member        Female         112   112           112         112
                     Male            69    69            69          69
       Normal        Female          72    72            72          72
                     Male            79    79            79          79
Giza   Member        Female         132   132           132         132
                     Male            62    62            62          62
       Normal        Female          68    68            68          68
                     Male            66    66            66          66

                             Quantity  Tax 5%  Sales  Date  Time  Payment  \
Branch Customer type Gender
Alex   Member        Female       112     112    112   112   112      112
                     Male          78      78     78    78    78       78
       Normal        Female        75      75     75    75    75       75
                     Male          75      75     75    75    75       75
Cairo  Member        Female       112     112    112   112   112      112
                     Male          69      69     69    69    69       69
       Normal        Female        72      72     72    72    72       72
                     Male          79      79     79    79    79       79
Giza   Member        Female       132     132    132   132   132      132
                     Male          62      62     62    62    62       62
       Normal        Female        68      68     68    68    68       68
                     Male          66      66     66    66    66       66

                             cogs  gross margin percentage  gross income  \
Branch Customer type Gender
Alex   Member        Female   112                      112           112
                     Male      78                       78            78
       Normal        Female    75                       75            75
                     Male      75                       75            75
Cairo  Member        Female   112                      112           112
                     Male      69                       69            69
       Normal        Female    72                       72            72
                     Male      79                       79            79
Giza   Member        Female   132                      132           132
                     Male      62                       62            62
       Normal        Female    68                       68            68
                     Male      66                       66            66

                             Rating  Division  Month  Day  Hour  Time_Category
Branch Customer type Gender
Alex   Member        Female     112       112    112  112   112            112
                     Male        78        78     78   78    78             78
       Normal        Female      75        75     75   75    75             75
                     Male        75        75     75   75    75             75
Cairo  Member        Female     112       112    112  112   112            112
                     Male        69        69     69   69    69             69
       Normal        Female      72        72     72   72    72             72
                     Male        79        79     79   79    79             79
Giza   Member        Female     132       132    132  132   132            132
                     Male        62        62     62   62    62             62
       Normal        Female      68        68     68   68    68             68
                     Male        66        66     66   66    66             66

In [127]:
# Har City ka Top Product Line identify karo based on Sales

df.groupby('City')['Sales'].idxmax().apply(lambda x: df.loc[x, 'Product line'])

City
Mandalay      Home and lifestyle
Naypyitaw    Fashion accessories
Yangon       Fashion accessories
Name: Sales, dtype: str

In [132]:
# Har Branch ke andar highest Gross Income wala transaction identify karo.

df.groupby('Branch')['gross income'].idxmax().apply(lambda x: df.loc[x, 'Payment'])

Branch
Alex     Credit card
Cairo        Ewallet
Giza     Credit card
Name: gross income, dtype: str

In [134]:
# Sales ke basis par Rank column create karo aur har transaction ko rank do

df['Rank'] = df['Sales'].rank(ascending=False).astype(int)
df['Rank']

0      187
1      856
2      383
3      235
4      134
      ...
995    946
996      5
997    963
998    897
999    131
Name: Rank, Length: 1000, dtype: int64

In [145]:
#  Har transaction ke Sales ko uske City ke average Sales se compare karo aur "Above Average" / "Below Average" label lagao.

df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,...,cogs,gross margin percentage,gross income,Rating,Division,Month,Day,Hour,Time_Category,Rank
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,...,522.83,4.761905,26.1415,9.1,Medium,January,Saturday,13,Afternoon,187
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,...,76.40,4.761905,3.8200,9.6,Low,March,Friday,10,Morning,856
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,...,324.31,4.761905,16.2155,7.4,Medium,March,Sunday,13,Afternoon,383
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,...,465.76,4.761905,23.2880,8.4,Medium,January,Sunday,20,Evening,235
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,...,604.17,4.761905,30.2085,5.3,Medium,February,Friday,10,Morning,134
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,...,40.35,4.761905,2.0175,6.2,Low,January,Tuesday,13,Afternoon,946
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,...,973.80,4.761905,48.6900,4.4,High,March,Saturday,17,Afternoon,5
997,727-02-1313,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,...,31.84,4.761905,1.5920,7.7,Low,February,Saturday,13,Afternoon,963
998,347-56-2442,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,...,65.82,4.761905,3.2910,4.1,Low,February,Friday,15,Afternoon,897
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,...,618.38,4.761905,30.9190,6.6,Medium,February,Monday,13,Afternoon,131

In [147]:
g = df[df['City'] == "Yangon"]

In [157]:
df['Yangon_City_Categorization'] = g[g['Sales'] > g['Sales'].mean()]['Sales'].apply(lambda x: "Above Average" if x > g['Sales'].mean() else "Below Average")
df['Yangon_City_Categorization'].fillna("Unknown", inplace=True)

C:\Users\great\AppData\Local\Temp\ipykernel_25920\3351312075.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Yangon_City_Categorization'].fillna("Unknown", inplace=True)

0      Above Average
1            Unknown
2      Above Average
3      Above Average
4      Above Average
           ...
995          Unknown
996          Unknown
997          Unknown
998          Unknown
999    Above Average
Name: Yangon_City_Categorization, Length: 1000, dtype: str

In [159]:
g1 = df[df['City'] == "Naypyitaw"]
g1

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,...,gross income,Rating,Division,Month,Day,Hour,Time_Category,Rank,fg,Yangon_City_Categorization
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,...,3.8200,9.6,Low,March,Friday,10,Morning,856,NaN,NaN
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,...,29.8865,4.1,Medium,March,Monday,18,Evening,143,NaN,NaN
7,315-22-5665,Giza,Naypyitaw,Member,Female,Home and lifestyle,73.56,10,36.7800,772.3800,...,36.7800,8.0,High,February,Sunday,11,Morning,69,NaN,NaN
20,300-71-4605,Giza,Naypyitaw,Member,Female,Electronic accessories,86.04,5,21.5100,451.7100,...,21.5100,4.8,Medium,February,Monday,11,Morning,272,NaN,NaN
34,183-56-6882,Giza,Naypyitaw,Member,Female,Food and beverages,99.42,4,19.8840,417.5640,...,19.8840,7.5,Medium,February,Wednesday,10,Morning,302,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,148-41-7930,Giza,Naypyitaw,Normal,Male,Health and beauty,99.96,7,34.9860,734.7060,...,34.9860,6.1,High,January,Wednesday,10,Morning,90,NaN,NaN
984,189-40-5216,Giza,Naypyitaw,Normal,Male,Electronic accessories,96.37,7,33.7295,708.3195,...,33.7295,6.0,High,January,Wednesday,11,Morning,104,NaN,NaN
988,267-62-7380,Giza,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.1700,864.5700,...,41.1700,4.3,High,March,Friday,19,Evening,34,NaN,NaN
994,652-49-6720,Giza,Naypyitaw,Member,Female,Electronic accessories,60.95,1,3.0475,63.9975,...,3.0475,5.9,Low,February,Monday,11,Morning,905,NaN,NaN
995,233-67-5758,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,...,2.0175,6.2,Low,January,Tuesday,13,Afternoon,946,NaN,NaN

In [ ]:
df['Naypyitaw_City_Categorization'] = g1[g1['Sales'] > g1['Sales'].mean()]['Sales'].apply(lambda x: "Above Average" if x > g1['Sales'].mean() else "Below Average")
df['Naypyitaw_City_Categorization'].fillna("Unknown", inplace=True)

C:\Users\great\AppData\Local\Temp\ipykernel_25920\1046354183.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Naypyitaw_City_Categorization'].fillna("Unknown", inplace=True)

0      Unknown
1      Unknown
2      Unknown
3      Unknown
4      Unknown
        ...
995    Unknown
996    Unknown
997    Unknown
998    Unknown
999    Unknown
Name: Naypyitaw_City_Categorization, Length: 1000, dtype: str

In [164]:
g2 = df[df['City'] == "Mandalay"]
g2

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,...,Rating,Division,Month,Day,Hour,Time_Category,Rank,fg,Yangon_City_Categorization,Naypyitaw_City_Categorization
9,692-92-5582,Cairo,Mandalay,Member,Female,Food and beverages,54.84,3,8.226,172.746,...,5.9,Low,February,Wednesday,13,Afternoon,648,NaN,NaN,NaN
10,351-62-0822,Cairo,Mandalay,Member,Female,Fashion accessories,14.48,4,2.896,60.816,...,4.5,Low,February,Wednesday,18,Evening,910,NaN,NaN,NaN
11,529-56-3974,Cairo,Mandalay,Member,Female,Electronic accessories,25.51,4,5.102,107.142,...,6.8,Low,March,Saturday,17,Afternoon,773,NaN,NaN,NaN
15,299-46-1805,Cairo,Mandalay,Member,Female,Sports and travel,93.72,6,28.116,590.436,...,4.5,Medium,January,Tuesday,16,Afternoon,164,NaN,NaN,NaN
19,319-50-3348,Cairo,Mandalay,Member,Female,Home and lifestyle,40.30,2,4.030,84.630,...,4.4,Low,March,Monday,15,Afternoon,847,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987,552-44-5977,Cairo,Mandalay,Member,Male,Health and beauty,62.00,8,24.800,520.800,...,6.2,Medium,January,Thursday,19,Evening,211,NaN,NaN,NaN
989,430-53-4718,Cairo,Mandalay,Member,Male,Health and beauty,75.37,8,30.148,633.108,...,8.4,Medium,January,Monday,15,Afternoon,136,NaN,NaN,NaN
991,602-16-6955,Cairo,Mandalay,Normal,Female,Sports and travel,76.60,10,38.300,804.300,...,6.0,High,January,Thursday,18,Evening,57,NaN,NaN,NaN
993,690-01-6631,Cairo,Mandalay,Normal,Male,Fashion accessories,17.49,10,8.745,183.645,...,6.6,Low,February,Friday,18,Evening,621,NaN,NaN,NaN
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.690,1022.490,...,4.4,High,March,Saturday,17,Afternoon,5,NaN,NaN,NaN

In [165]:
df['Mandalay_City_Categorization'] = g2[g2['Sales'] > g2['Sales'].mean()]['Sales'].apply(lambda x: "Above Average" if x > g2['Sales'].mean() else "Below Average")
df['Mandalay_City_Categorization'].fillna("Unknown", inplace=True)

C:\Users\great\AppData\Local\Temp\ipykernel_25920\953605515.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Mandalay_City_Categorization'].fillna("Unknown", inplace=True)

0            Unknown
1            Unknown
2            Unknown
3            Unknown
4            Unknown
           ...
995          Unknown
996    Above Average
997          Unknown
998          Unknown
999          Unknown
Name: Mandalay_City_Categorization, Length: 1000, dtype: str

In [168]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,...,Day,Hour,Time_Category,Rank,fg,Yangon_City_Categorization,Naypyitaw_City_Categorization,Mandalay_City_Categorization,City_Avg_Sales,Sales_Label
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,...,Saturday,13,Afternoon,187,Above Average,Above Average,NaN,NaN,312.354031,Above Average
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,...,Friday,10,Morning,856,NaN,NaN,NaN,NaN,337.099715,Below Average
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,...,Sunday,13,Afternoon,383,Above Average,Above Average,NaN,NaN,312.354031,Above Average
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,...,Sunday,20,Evening,235,Above Average,Above Average,NaN,NaN,312.354031,Above Average
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,...,Friday,10,Morning,134,Above Average,Above Average,NaN,NaN,312.354031,Above Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,...,Tuesday,13,Afternoon,946,NaN,NaN,NaN,NaN,337.099715,Below Average
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,...,Saturday,17,Afternoon,5,NaN,NaN,NaN,Above Average,319.872506,Above Average
997,727-02-1313,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,...,Saturday,13,Afternoon,963,NaN,NaN,NaN,NaN,312.354031,Below Average
998,347-56-2442,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,...,Friday,15,Afternoon,897,NaN,NaN,NaN,NaN,312.354031,Below Average
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,...,Monday,13,Afternoon,131,Above Average,Above Average,NaN,NaN,312.354031,Above Average

In [167]:
df['City_Avg_Sales'] = df.groupby('City')['Sales'].transform('mean')

df['Sales_Label'] = np.where(df['Sales'] > df['City_Avg_Sales'], 
                              "Above Average", 
                              "Below Average")

In [169]:
#  Aise transactions identify karo jahan Sales > City Average Sales AND Rating > 8.  

df[(df['Sales'] > df['City_Avg_Sales']) & (df['Rating'] > 8)]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,...,Day,Hour,Time_Category,Rank,fg,Yangon_City_Categorization,Naypyitaw_City_Categorization,Mandalay_City_Categorization,City_Avg_Sales,Sales_Label
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,...,Saturday,13,Afternoon,187,Above Average,Above Average,NaN,NaN,312.354031,Above Average
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,...,Sunday,20,Evening,235,Above Average,Above Average,NaN,NaN,312.354031,Above Average
13,252-56-2699,Alex,Yangon,Member,Female,Food and beverages,43.19,10,21.5950,453.4950,...,Thursday,16,Afternoon,270,Above Average,Above Average,NaN,NaN,312.354031,Above Average
25,227-03-5010,Alex,Yangon,Member,Female,Home and lifestyle,52.59,8,21.0360,441.7560,...,Friday,19,Evening,279,Above Average,Above Average,NaN,NaN,312.354031,Above Average
28,145-94-9061,Cairo,Mandalay,Member,Female,Food and beverages,88.36,5,22.0900,463.8900,...,Friday,19,Evening,258,NaN,NaN,NaN,Above Average,319.872506,Above Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,384-59-6655,Alex,Yangon,Member,Female,Food and beverages,98.66,9,44.3970,932.3370,...,Tuesday,15,Afternoon,20,Above Average,Above Average,NaN,NaN,312.354031,Above Average
970,746-04-1077,Cairo,Mandalay,Member,Female,Food and beverages,84.63,10,42.3150,888.6150,...,Tuesday,11,Morning,27,NaN,NaN,NaN,Above Average,319.872506,Above Average
976,221-25-5073,Alex,Yangon,Normal,Female,Food and beverages,74.66,4,14.9320,313.5720,...,Monday,10,Morning,416,Above Average,Above Average,NaN,NaN,312.354031,Above Average
985,374-38-5555,Cairo,Mandalay,Normal,Female,Fashion accessories,63.71,5,15.9275,334.4775,...,Thursday,19,Evening,391,NaN,NaN,NaN,Above Average,319.872506,Above Average
989,430-53-4718,Cairo,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,...,Monday,15,Afternoon,136,NaN,NaN,NaN,Above Average,319.872506,Above Average